"""change1 diaries

Revision ID: 22fce634b01b
Revises: 3385a3cf431d
Create Date: 2026-06-09 16:35:54.504538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22fce634b01b'
down_revision: Union[str, Sequence[str], None] = '3385a3cf431d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diaries', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('diaries', 'title',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('diaries', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diaries', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('diaries', 'title',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('diaries', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
