name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: my_project_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DATABASE_URI: postgresql://postgres:postgres@localhost:5432/my_project_test
          SECRET_KEY: test_secret
          TEST_DATABASE_URI: postgresql://postgres:postgres@localhost:5432/my_project_test
          TEST_SECRET_KEY: test_secret
        run: alembic upgrade head

      - name: Run tests
        env:
          DATABASE_URI: postgresql://postgres:postgres@localhost:5432/my_project_test
          TEST_DATABASE_URI: postgresql://postgres:postgres@localhost:5432/my_project_test
          SECRET_KEY: test_secret
          TEST_SECRET_KEY: test_secret
        run: python -m pytest tests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: Sofia-so/flask-pet-project:latest
